version: '2.0'
services:
  frontend:
    image: vburmus/frontend:v2
    build:
      context: frontend
      dockerfile: Dockerfile
    environment:
      - envs
    ports:
      - 8081:3000
  backend:
    image: vburmus/backend:v2
    build:
      context: backend
      dockerfile: Dockerfile
    environment:
      - envs
    ports:
      - 8080:8080